### ISSUE TITLE
The value or constructor 'bindEvent' is not defined

### ISSUE THREAD

**Issue by zakaluka** [davedawkins/sutil-template-app#1]
It looks like `bindEvent` was removed as part of commit .  However, the template is still relying on this.  

I am just getting started with Sutil, so not sure what this is supposed to be.  I have changed is based on the corresponding change made to the Sutil repo, but I don't see any 'isInvalid'-related formatting on the page.

**Comment by zakaluka** [comment]
Commit where bindEvent was removed: https://github.com/davedawkins/Sutil/commit/39950c497b051c0cb052b4260828d17dc13aae64

**Comment by davedawkins** [comment]
Thank you! I need to learn how to use appveyor so that these dependent projects are rebuilt and tested against new releases of Sutil. I usually do them by hand, and this time I clearly didn't.

The formatting comes from the bindClass - we're adding and removing "is-danger" as a class and the styling colors the text accordingly.

I'll merge your PR and then tweak it if necessary. You can compare yours with mine.

**Comment by davedawkins** [comment]
The PR seems to work great - nice job. I wondered if we should have `isInvalid` start with a `true` value to be consistent with what happens if you enter a character and then delete it. 

The validity check itself looks to be very basic, and I probably intended the developer to add app-specific checks (like, should be a valid email address / look for invalid characters etc).

Does this help explain what's going on?
